### ISSUE TITLE
Unable to download the videos of web-vid using the provided python script

### ISSUE THREAD

**Issue by XuecWu** [zeroQiaoba/AffectGPT#3]
Thank you for your great works!
As described above, using the script provided in **AffectGPT/AffectGPT/instruction-dataset/VideoChat/download.py**, I can not download the videos.

I confirm that I have prepared the csv files well.
However, when I run the script in `python download.py --csv_path=results_10M_val.csv   --partitions=4 --part=2 --data_dir=./data --processes=8 --json_path='./videochat_instruct_11k.json'`, I get something as follows:

> Spawning 0 jobs for page 196301_196350
> Spawning 0 jobs for page 196401_196450
> Spawning 0 jobs for page 196501_196550
> Spawning 0 jobs for page 196601_196650
> Spawning 0 jobs for page 196651_196700
> Spawning 0 jobs for page 196701_196750
> Spawning 0 jobs for page 196751_196800
> Spawning 0 jobs for page 196801_196850
> Spawning 0 jobs for page 197001_197050
> Spawning 0 jobs for page 197151_197200
> Spawning 0 jobs for page 197251_197300
> Spawning 0 jobs for page 197301_197350
> Spawning 0 jobs for page 197501_197550
> Spawning 0 jobs for page 197651_197700
> Spawning 0 jobs for page 197701_197750
> Spawning 0 jobs for page 197751_197800
> Spawning 0 jobs for page 197851_197900
> Spawning 0 jobs for page 198201_198250
> Spawning 0 jobs for page 198251_198300
> Spawning 0 jobs for page 198401_198450
> Spawning 0 jobs for page 198601_198650
> Spawning 0 jobs for page 198901_198950
> Spawning 0 jobs for page 199201_199250
> Spawning 0 jobs for page 199251_199300
> Spawning 0 jobs for page 199501_199550
> Spawning 0 jobs for page 199651_199700
> Spawning 0 jobs for page 199701_199750
> Spawning 0 jobs for page 199801_199850

And there are no videos.
What should I do to download the videos correctly?

Looking forward to your reply!
Thank you.

**Comment by XuecWu** [comment]
Although **the instruction tuning data of videochat2 is not used**, I still run the training command, _i.e._,` torchrun --nproc_per_node=8 train.py --cfg-path=./train_configs/multimodal_llama_stage3_finetune.yaml`, after moving the code of videochat2 in `multimodal_llama_stage3_finetune.yaml`.
And I encounter the following errors:

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at models/vicuna-7b-v0 and are newly initialized: ['model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.27.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.30.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.28.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781616 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781617 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781618 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781620 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781621 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781622 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2781623 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 (pid: 2781619) of binary: /home/xxx/.conda/envs/videollama3/bin/python
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/videollama3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.0', 'console_scripts', 'torchrun')())
  File "/home/xxx/.conda/envs/videollama3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xxx/.conda/envs/videollama3/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/xxx/.conda/envs/videollama3/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/xxx/.conda/envs/videollama3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxx/.conda/envs/videollama3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
========================================================
train.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-08_18:50:42
  host      : user-SYS
  rank      : 3 (local_rank: 3)
  exitcode  : -9 (pid: 2781619)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 2781619
========================================================

Because I do not see any obvious errors, I have no idea how to solve this issue. 
Could give me some advice to address this issue?

Any reply will be appreciated greatly.
Thanks a lot!

**Comment by zeroQiaoba** [comment]
The official dataset is updated. The current version totally depends on MER-Caption+. And other instrusction datasets are no longer needed.
